### ISSUE TITLE
random parcellation code

### ISSUE THREAD

**Issue by snapfinger** [DiedrichsenLab/DCBC#2]
Hi, in the HBM paper you use random parcellation with various #parcels as a baseline, but I only found the random parcellations in this repo not the code for generating them. Could you also include the code?

**Comment by dzhi1993** [comment]
Hi @snapfinger, thanks for raising the question. Sure, you can generate random parcellations using the script at [here](https://github.com/DiedrichsenLab/surfAnalysis/blob/master/development/surf_icosahedron.m).

**Comment by snapfinger** [comment]
Thanks!
